apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processor
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: neural-network-processor
        image: ai-processor:latest
        ports:
        - containerPort: 8080
        env:
        - name: AI_SECURITY_TOKEN
          value: "R4nd0mT0k3n"
        - name: ENABLE_DEBUG_MODE
          value: "false"
        volumeMounts:
        - mountPath: /dev/shm
          name: memory-cache
      volumes:
      - name: memory-cache
        emptyDir: {}
